services:
  mongodb:
    image: mongo
    container_name: duck_cook_auth_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - mongo.env  
    networks:
      - monitoring-network         
  duck_cook_recipe:
    build:
      dockerfile: ./docker/go.Dockerfile
      context: .
    container_name: duck_cook_auth
    networks:
      - monitoring-network
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - prometheus  
    env_file:
      - .env

networks:
  monitoring-network:
    driver: bridge   
volumes:
  mongodb_data:    