services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - cache:/data
    container_name: duck_cook_auth_redis
    env_file:
      - redis.env    
    networks:
      - monitoring-network
  mongodb:
    image: mongo
    container_name: duck_cook_auth_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - mongo.env  
    networks:
      - monitoring-network         
  duck_cook_recipe:
    build:
      dockerfile: ./docker/go.Dockerfile
      context: .
    container_name: duck_cook_auth
    networks:
      - monitoring-network
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env

networks:
  monitoring-network:
    driver: bridge   
volumes:
  mongodb_data:    
  cache: