definitions:
  entity.CommentRecipe:
    properties:
      id:
        type: string
      message:
        type: string
    type: object
  entity.Recipe:
    properties:
      description:
        type: string
      id:
        type: string
      idUser:
        type: string
      imageUrl:
        example: url da imagem
        format: string
        type: string
      preparationTime:
        example: 600
        format: int64
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /recipe:
    post:
      consumes:
      - application/json
      description: Adicionar uma nova receita
      parameters:
      - description: Dados da receita
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/entity.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Recipe'
      summary: Adicionar nova receita
      tags:
      - recipe
    put:
      consumes:
      - application/json
      description: Atualizar a receita
      parameters:
      - description: Dados da receita
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/entity.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Recipe'
      summary: Atualizar a receita
      tags:
      - recipe
  /recipe/{id}:
    delete:
      consumes:
      - application/json
      description: Adicionar uma nova receita
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Adicionar nova receita
      tags:
      - recipe
    get:
      consumes:
      - application/json
      description: Retorna a receita
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Recipe'
      summary: Retorna a receita
      tags:
      - recipe
  /recipe/{id}/comment:
    get:
      consumes:
      - application/json
      description: likes da receita
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
      summary: Likes da receita
      tags:
      - like-recipe
  /user/{id}/recipe:
    get:
      consumes:
      - application/json
      description: Retonar as receitas do usuário
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Recipe'
      summary: Retonar as receitas do usuário
      tags:
      - recipe
  /user/{id}/recipe/{idRecipe}/comment:
    post:
      consumes:
      - application/json
      description: Comenta na receita baseado no usuário
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: path
        name: idRecipe
        required: true
        type: integer
      - description: Comentário
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/entity.CommentRecipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Recipe'
      summary: Comenta na receita
      tags:
      - comment-recipe
  /user/{id}/recipe/{idRecipe}/comment/{idComment}:
    delete:
      consumes:
      - application/json
      description: Delete o comentário da receita
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Recipe ID
        in: path
        name: idRecipe
        required: true
        type: integer
      - description: Comment ID
        in: path
        name: idComment
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Deleta o comentário da receita
      tags:
      - comment-recipe
  /user/{id}/recipe/{idRecipe}/like:
    post:
      consumes:
      - application/json
      description: Like na receita baseado no usuário
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: path
        name: idRecipe
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Recipe'
      summary: Like na receita
      tags:
      - like-recipe
  /user/{id}/recipe/{idRecipe}/like/{idLike}:
    delete:
      consumes:
      - application/json
      description: Delete o like da receita
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Recipe ID
        in: path
        name: idRecipe
        required: true
        type: integer
      - description: Like ID
        in: path
        name: idLike
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Deleta o like da receita
      tags:
      - like-recipe
swagger: "2.0"
